CREATE DATABASE IF NOT EXISTS ecommerce;
USE ecommerce;

CREATE TABLE IF NOT EXISTS utenti (
   id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
   nome_utente VARCHAR(40) NOT NULL UNIQUE,
   pw_hash VARCHAR(255) NOT NULL,
   privilegi ENUM('visualizzatore', 'creatore') NOT NULL,
   data_creazione DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS indirizzi (
   id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
   id_utente INT UNSIGNED NOT NULL REFERENCES utenti(id),
   indirizzo TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS carrelli(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	quantitativo INT UNSIGNED NOT NULL,
	id_prodotto INT UNSIGNED REFERENCES prodotti(id),
	id_utente INT UNSIGNED NOT NULL REFERENCES utenti(id)
);

CREATE TABLE IF NOT EXISTS categorie(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	titolo VARCHAR(255) NOT NULL,
	descrizione TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS prodotti(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	titolo VARCHAR(255) NOT NULL,
	descrizione TEXT NOT NULL,
	tipologia ENUM('prodotto', 'accessorio') NOT NULL,
	prezzo DECIMAL(10, 2) NOT NULL,
	data_aggiunta DATETIME NOT NULL,
	id_creatore INT UNSIGNED NOT NULL REFERENCES utenti(id),
	id_prodotto INT UNSIGNED REFERENCES prodotti(id)
);

CREATE TABLE IF NOT EXISTS categorie_prodotti(
	id_prodotto INT UNSIGNED REFERENCES prodotti(id),
	id_categoria INT UNSIGNED REFERENCES categoria(id)	
); 

CREATE TABLE IF NOT EXISTS immagini(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_prodotto INT UNSIGNED REFERENCES prodotti(id),
	percorso VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ordini(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_utente INT UNSIGNED NOT NULL REFERENCES utenti(id),
	costo_totale DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS dettagli_ordini(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_ordine INT UNSIGNED NOT NULL REFERENCES ordini(id),
	id_prodotto INT UNSIGNED NOT NULL REFERENCES prodotti(id),
	costo DECIMAL(10, 2) NOT NULL,
	quantitativo INT UNSIGNED NOT NULL,
	data_ordine DATETIME NOT NULL
);

