CREATE DATABASE IF NOT EXISTS ecommerce;
USE ecommerce;

CREATE TABLE IF NOT EXISTS utenti(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome_utente VARCHAR(40) NOT NULL UNIQUE,
	pw_hash VARCHAR(255) NOT NULL,
	privilegi ENUM('0', '1') NOT NULL,
	data_creazione DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS prodotti(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	titolo VARCHAR(255) NOT NULL,
	descrizione TEXT NOT NULL,
	prezzo DECIMAL(10, 2) NOT NULL,
	data_aggiunta DATETIME NOT NULL,
	id_creatore INT UNSIGNED NOT NULL REFERENCES utenti(id),
	id_prodotto INT UNSIGNED REFERENCES prodotti(id)
);

CREATE TABLE IF NOT EXISTS ordini(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_prodotto INT UNSIGNED NOT NULL REFERENCES prodotti(id),
	id_utente INT UNSIGNED NOT NULL REFERENCES utenti(id),
	data_ordine DATETIME NOT NULL
);